Bachelor/TecnologieWeb/Laboratory/Biblioteca/Biblioteca/Biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from .adminDB import erase_DB,init_DB


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestione/',include('gestione.urls'), name = "gestione")
]

erase_DB()
init_DB()

Bachelor/TecnologieWeb/Laboratory/Biblioteca/Biblioteca/gestione/urls.py
from django.contrib import admin
from django.urls import path
from .views import show_libri,show_librimattoni, show_libriautore, show_autore,crea_libro, modifica_libro, cancella_libro

app_name = "gestione"


urlpatterns = [
    path('listalibri/', show_libri, name = "listalibri"),
    path('listalibrimattoni/', show_librimattoni, name = "listalibrimattoni"),
    path('listalibriautore/', show_libriautore, name = "listalibriautore"),
    path('autore/<str:autore>/',show_autore, name = "autore"),
    path('crealibro/', crea_libro, name = "crealibro"),
    path('modificalibro/<str:autore>/<str:titolo>', modifica_libro, name = "modificalibro"),
    path('cancellalibro/', cancella_libro, name = "cancellalibro")

]

Bachelor/TecnologieWeb/Laboratory/Biblioteca/Biblioteca/gestione/models.py
from django.db import models


class Libro(models.Model):
    titolo = models.CharField(max_length=200)
    autore = models.CharField(max_length=200)
    Pagine = models.IntegerField(default=100)
    data_prestito = models.DateField(default=None)

    def __str__(self):
        out = self.titolo + " " + self.autore + " " + str(self.Pagine)
        if self.data_prestito == None:
            out += " disponibile"
        else:
            out += " in prestito dal " + str(self.data_prestito)
        return out

    

Bachelor/TecnologieWeb/Laboratory/Biblioteca/Biblioteca/gestione/views.py
from django.shortcuts import render,HttpResponse, get_object_or_404
from .models import Libro
from django.utils import timezone

# Create your views here.

MATTONE_THRESHOLD = 300

def show_libri(request):

    templ = "gestione/listalibri.html"

    ctx = {"title": "Lista Libri", "listalibri": Libro.objects.all()}

    return render(request, template_name = templ, context=ctx)


def show_librimattoni(request):

    templ = "gestione/listalibri.html"
    #lista_filtrata = Libro.objects.filter(pagine__gte=MATTONE_THRESHOLD)
    lista_filtrata = Libro.objects.exclude(Pagine__lt=MATTONE_THRESHOLD)

    ctx = {"title": "Lista Libri", "listalibri": lista_filtrata}

    return render(request, template_name = templ, context=ctx)

def show_libriautore(request):
    templ  = "gestione/listalibri.html"

    lista_filtrata = Libro.objects.filter(autore__exact=request.GET["autore"])
    #lista_filtrata = Libro.objects.exclude(pagine__lt=MATTONE_THRESHOLD)
    ctx = {"title": "Lista Libri", "listalibri": lista_filtrata}
    return render(request, template_name = templ, context=ctx)


def show_autore(request,autore):
    templ  = "gestione/listalibri.html"

    lista_filtrata = Libro.objects.filter(autore__exact=autore)
    #lista_filtrata = Libro.objects.exclude(pagine__lt=MATTONE_THRESHOLD)

    ctx = {"title": "Lista Libri", "listalibri": lista_filtrata}

    return render(request, template_name = templ, context=ctx)


def crea_libro(request):
    message = ""

    if "autore" in request.GET and "titolo" in request.GET:
        autore = request.GET["autore"]
        titolo = request.GET["titolo"]
        pag = 100

        try:
            pag = int(request.GET["pagine"])
        except:
            message = "Pagine non valide. Inserite pagine di default"

        l = Libro()
        l.autore = autore
        l.titolo = titolo
        l.Pagine = pag
        l.data_prestito = timezone.now()

        try:
            l.save()
            message = "Creazione libro riuscita!" + message
        except Exception as e:
            message = "Errore nella creazione libro" + str(e)

    return render(request, template_name = "gestione/crealibro.html", context={"title": "Crea Libro", "message": message})


def modifica_libro(request, autore, titolo):

    message = ""
    libro = get_object_or_404(Libro, autore=autore, titolo=titolo)

    if "autore" in request.GET and "titolo" in request.GET:
        autore = str(request.GET["autore"])
        titolo = str(request.GET["titolo"])
        pag = 100

        try:
            pag = int(request.GET["pagine"])
        except:
            message = "Pagine non valide. Inserite pagine di default"

        libro.autore = autore
        libro.titolo = titolo
        libro.Pagine = pag

        try:
            libro.save()
            message = "Modifica libro riuscita!" + message
        except Exception as e:
            message = "Errore nella modifica libro" + str(e)

    return render(request, template_name = "gestione/modificalibro.html", context={"title": "Modifica Libro", "libro": libro, "message": message})

def cancella_libro(request):

    msg = ""
    
    if "libro" in request.GET:
        s = request.GET["libro"]
        s = s[:s.index(':')]
        try:
            l = Libro.objects.get(pk=int(s))
            l.delete()
            msg = "Rimozione completata!"
        except Exception as e:
            msg = "Errore nella cancellazione dell'entry " + str(e)
        

    return render(request, template_name = "gestione/cancellalibro.html", context={"title":"Cancella libro","libri": Libro.objects.all(),"message":msg})

Bachelor/TecnologieWeb/Laboratory/Biblioteca/Biblioteca/gestione/templates/gestione/cancellalibro.html
{% extends 'base.html' %}

{% block head %}{% endblock head %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<center>
    <h1> {{ title }} </h1>

    {% if message == "" %}

    <form action="/gestione/cancellalibro" method="GET">
        <label for="libro">Scegli il libro da cancellare:</label>
        <select name="libro" id="libro">
          {% for l in libri %}
          
          <option>{{ l.pk }}: {{l.autore}} {{l.titolo}} </option>
          
          {% endfor %}

        </select>
        <br><br>
        <input type="submit" value="Elimina">
    </form>
    
    {% else %}
        {{ message }}
        <a href = "{% url 'gestione:listalibri' %}"> Lista Libri </a>
    
    {% endif %}
    

</center>



{% endblock content %}

Bachelor/TecnologieWeb/Laboratory/Biblioteca/Biblioteca/gestione/templates/gestione/crealibro.html
{% extends 'base.html' %}

{% block head %}{% endblock head %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<center>
    <h1> {{ title }} </h1>

    {% if message == "" %}

    <form action = "/gestione/crealibro"> 
        <label for = "Autore">Autore:</label> <br>
        <input type="text" id="autore" name="autore"> <br>
        <label for = "Titolo">Titolo: </label> <br>
        <input type="text" id="titolo" name="titolo"> <br>
        <label for = "Pagine">Pagine: </label> <br>
        <input type="text" id="pagine" name="pagine"> <br> <br>
        <input type="submit" value="Crea Entry"> <br>
    </form>
    
    {% else %}

    <p> {{ message }} </p>
    <a href = "{% url 'gestione:listalibri' %}"> Lista Libri </a>

    {% endif %}

</center>



{% endblock content %}

Bachelor/TecnologieWeb/Laboratory/Biblioteca/Biblioteca/gestione/templates/gestione/listalibri.html
{% extends 'base.html' %}

{% block head %}{% endblock head %}
{% block title %}{{ title }}{% endblock title %}


{% block content %}

<center>
<h1> {{ title }} </h1>

{% if listalibri.count > 0 %}
    <p> Ci sono {{ listalibri.count }} nel database </p>
    <ul>
        {% for l in listalibri %}
        
            <li> {{ l }} </li>
        
        {% endfor %}
    </ul>
{% else %}
    <p> Non ci sono libri </p>

{% endif %}

</center>

{% endblock  %}

Bachelor/TecnologieWeb/Laboratory/Biblioteca/Biblioteca/gestione/templates/gestione/modificalibro.html
{% extends 'base.html' %}

{% block head %}{% endblock head %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<center>
    <h1> {{ title }} </h1>

    {% if message == "" %}

    <form action = "/gestione/modificalibro/{{libro.autore}}/{{libro.titolo}}"> 
        <label for = "Autore">Autore:</label> <br>
        <input type="text" id="autore" name="autore" value = "{{ libro.autore }}"> <br>
        <label for = "Titolo">Titolo: </label> <br>
        <input type="text" id="titolo" name="titolo" value=" {{ libro.titolo }}"> <br>
        <label for = "Pagine">Pagine: </label> <br>
        <input type="text" id="pagine" name="pagine" value = " {{libro.Pagine}}"> <br> <br>
        <input type="submit" value="Crea Entry"> <br>
    </form>
    
    {% else %}
        {{ message }}
        <a href = "{% url 'gestione:listalibri' %}"> Lista Libri </a>
    
    {% endif %}
    

</center>



{% endblock content %}

Bachelor/TecnologieWeb/Laboratory/Biblioteca/Biblioteca/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block head %} {% endblock %}
    <title> {% block title %}{% endblock %}</title>
</head>

<body>
{% block content %}
{% endblock %}
</body>

</html>